# Generated by Django 5.1.3 on 2024-11-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
