# Generated by Django 5.1.3 on 2024-11-13 10:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
